### ISSUE TITLE
Support for surround output.

### ISSUE THREAD

**Issue by drewbitllama** [resonance-audio/resonance-audio-web-sdk#1]
In addition to binaural and ambisonic output, allow the export of arbitrary speaker layouts, with presets for common layouts such as stereo, 5.1, and 7.1.

**Comment by jkammerl** [comment]
Marked as "feature request"

**Comment by scriptify** [comment]
Hello!
Are there any plans to implement this feature?
It would be really cool if e.g. Apple's Spatial Audio with AirPods would work out of the box.  As there wasn't any activity for 3 years, I assume the development of this project has stalled. If you could guide me in the right direction I'd love trying to implement that 🤞
