### ISSUE TITLE
Resonance Audio does not work in Firefox

### ISSUE THREAD

**Issue by ianpetrarca** [resonance-audio/resonance-audio-web-sdk#8]
Google resonance does not seem to work with Firefox. The official examples page gives this error:

_The HTMLMediaElement passed to createMediaElementSource has a cross-origin resource, the node will output silence._

Link: https://cdn.rawgit.com/resonance-audio/resonance-audio-web-sdk/master/examples/index.html

Additionally, I am working on a project right now that uses Resonance with WebVR and there is no reverb output while it's running in Firefox. It runs perfectly in Chrome. 

https://spatialsoundbox.firebaseapp.com/

Any thoughts why this might be happening?

Ian

**Comment by brianchirls** [comment]
I can confirm both of these issues. Here is another example site where there is reverb in Chrome but not Firefox: https://demo.datavized.com/drums/

My architecture is different from @ianpetrarca's, so it is very likely an issue with Resonance, not with his code.

**Comment by mgorzel** [comment]
I think it could be related to [this](https://bugzilla.mozilla.org/show_bug.cgi?id=937718) bug. It looks like Firefox requires the `crossOrigin` property of the `audio` element to be specified. Adding: `audioElement.crossOrigin = 'anonymous';` to the .js solved that for me.

**Comment by brianchirls** [comment]
@drewbitllama This does fix the cross origin bug, but it does not address the lack of reverb in Firefox. There does appear to be reverb in the samples, but not in @ianpetrarca's example, nor mine. Can we re-open this please?

I'm digging but haven't been able to find anything yet. I know there have been a handful of deprecations around the Web Audio API in the last few months and years, so perhaps there's a difference of implementation that's causing problems. I did see a warning in Firefox about using the deprecated doppler effect, but that seems to have gone away.

**Comment by drewbitllama** [comment]
Hi Brian / Ian, 

Can you open a separate issue re:Reverberation and create and share a simple demo demonstrating a lack of reverb (ideally the least code needed to reproduce the bug).

Thanks!
Drew
